project_id = "hkvuttothwfsioxdhgbb"

[functions.calculate-quote]
verify_jwt = false

[functions.sla-check]
verify_jwt = false

[functions.ai-analytics]
verify_jwt = false

[functions.ai-lead-analysis]
verify_jwt = false

[functions.send-email]
verify_jwt = false

[functions.stripe-checkout]
verify_jwt = false

[functions.stripe-webhook]
verify_jwt = false

[functions.social-publish]
verify_jwt = false
